name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute .NET Tasks
        uses: ./.github/actions/Dotnet-actions
        with:
          command: restore
          projects: '**/*.csproj'
          nugetConfigPath: 'NuGet.config'
          restoreArguments: '--force'
          noCache: true
          restoreDirectory: 'packages'
          verbosityRestore: 'minimal'
          arguments: '--configuration Release'
          publishTestResults: true
          testRunTitle: 'UnitTestResults'
          packagesToPack: '**/*.csproj'
          configuration: 'Release'
          packDirectory: 'artifacts'
          nobuild: true
          includesymbols: true
          includesource: true
          buildProperties: 'ContinuousIntegrationBuild=true'
          verbosityPack: 'detailed'
          publishWebProjects: true
          zipAfterPublish: true
          modifyOutputPath: true
          includeNuGetOrg: true
          publishPackageMetadata: true
          requestTimeout: '300'
