name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Dependencies
        uses: ./.github/actions/Dotnet-actions
        with:
          command: restore
          projects: '**/*.csproj'
          nugetConfigPath: ./NuGet.config
          packagesDirectory: "path/to/packages"
          restoreArguments: '--force'
          noCache: true
          nuGetPath: './nuget.exe' # Added nuGetPath
          nuGetVersion: '5.11.0'   # Added nuGetVersion

      - name: Build Project
        uses: ./.github/actions/Dotnet-actions
        with:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration Release'
          nuGetPath: './nuget.exe' # Added nuGetPath
          nuGetVersion: '5.11.0'   # Added nuGetVersion

      - name: Run Tests
        uses: ./.github/actions/Dotnet-actions
        with:
          command: test
          projects: '**/*.csproj'
          arguments: '--collect "Code coverage"'
          nuGetPath: './nuget.exe' # Added nuGetPath
          nuGetVersion: '5.11.0'   # Added nuGetVersion

      - name: Pack Project
        uses: ./.github/actions/Dotnet-actions
        with:
          command: pack
          projects: '**/*.csproj'
          arguments: '--configuration Release'
          nuGetPath: './nuget.exe' # Added nuGetPath
          nuGetVersion: '5.11.0'   # Added nuGetVersion

      - name: Publish Project
        uses: ./.github/actions/Dotnet-actions
        with:
          command: publish
          projects: '**/*.csproj'
          arguments: '--configuration Release'
          nuGetPath: './nuget.exe' # Added nuGetPath
          nuGetVersion: '5.11.0'   # Added nuGetVersion
