name: MAIN Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    uses: kiranvattikuti146/DOTNET-REUSABLE/.github/workflows/Dotnetreusable.yml@main
    with:
      runsOn: "windows-latest"
      dotnet-version: "7.0.x"
      code-coverage-enabled: true
      configuration: "Release"
      platform: "x64"
      run-in-parallel: true
      testPlan: "Plan1"
      testSuite: "SuiteA"
      testConfiguration: "Release"
      tcmTestRun: "1234"
      uiTests: false
      vsTestVersion: "latest"
      vstestLocation: "C:Program FilesMicrosoft Visual Studio2022EnterpriseCommon7IDEExtensionsTestPlatformvstest.console.exe"
      diagnosticsEnabled: true
      rerunFailedTests: true
      rerunType: "specific"
      rerunMaxAttempts: "3"
      dontDistribute: false
