name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Dependencies
        uses: ./.github/actions/Dotnet-actions
        with:
          command: restore
          projects: '**/*.csproj'
          nugetConfigPath: 'NuGet.config' # Optional, provide only if needed
          restoreArguments: '--force'
          noCache: true
          restoreDirectory: 'packages' # Optional, provide only if needed

      - name: Build Project
        uses: ./.github/actions/Dotnet-actions
        with:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration Release'

      - name: Run Tests
        uses: ./.github/actions/Dotnet-actions
        with:
          command: test
          projects: '**/*.csproj'
          arguments: '--collect "Code coverage"'

      - name: Pack Project
        uses: ./.github/actions/Dotnet-actions
        with:
          command: pack
          projects: '**/*.csproj'
          arguments: '--configuration Release'

      - name: Publish Project
        uses: ./.github/actions/Dotnet-actions
        with:
          command: publish
          projects: '**/*.csproj'
          arguments: '--configuration Release'
