name: Main Workflow

on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 

jobs: 
  build-solution: 
    name: Build Solution 
    needs: nuget-restore 
    uses: kirandevops1993/DINESH-VSBUILD-REUSABLE/.github/workflows/reusable.yml@main 
    with: 
      runsOn: "windows-latest"
      solution: "*/*.sln" 
      vsVersion: "latest" 
      msbuildArgs: "/p:Optimize=true" 
      platform: "Any CPU" 
      configuration: "Release" 
      clean: true 
      maximumCpuCount: true 
      restoreNugetPackages: true 
      msbuildArchitecture: "x86" 
      logProjectEvents: true 
      createLogFile: true 
      logFileVerbosity: "normal" 
      enableDefaultLogger: true 
      customVersion: "1.0.0" 
