name: Main Workflow

on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 

jobs: 
  nuget-restore: 
    name: NuGet Restore 
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main 
    with: 
      solution: OrchardCore.sln 
      nugetConfigPath: ./NuGet.config 
      packagesDirectory: "path/to/packages" 
      verbosity: "detailed" 
      nuGetRestoreArgs: " " 
      restoreMode: "restore" 
      noCache: true 
      nuGetVersion: "5.9.0" 
      nuGetPath: ./nuget.exe 
      searchPattern: "*.csproj" 
      outputdir: "path/to/output" 
      includeSymbols: true 
      versionByBuild: true 
      versionEnvVar: "BUILD_VERSION" 
      majorVersion: 1 
      minorVersion: 0 
      patchVersion: 0 
      configurationToPack: "Release" 
      buildProperties: "Configuration=Release" 
      nuGetAdditionalArgs: "--verbosity detailed" 
      nuGetFeedType: "AzureArtifacts" 
      feedName: "YourFeedName" 
      skipDuplicate: true 

    secrets: 
      apiKey: ${{ secrets.AZURE_DEVOPS_PAT }} 

  build-solution: 
    name: Build Solution 
    needs: nuget-restore 
    uses: kirandevops1993/DINESH-VSBUILD-REUSABLE/.github/workflows/reusable.yml@main 
    with: 
      solution: "*/*.sln" 
      vsVersion: "latest" 
      msbuildArgs: "/p:Optimize=true" 
      platform: "Any CPU" 
      configuration: "Release" 
      clean: true 
      maximumCpuCount: true 
      restoreNugetPackages: true 
      msbuildArchitecture: "x86" 
      logProjectEvents: true 
      createLogFile: true 
      logFileVerbosity: "normal" 
      enableDefaultLogger: true 
      customVersion: "1.0.0" 

  run-tests: 
    name: Run Tests 
    needs: build-solution 
    runs-on: windows-latest # This specifies the runner for the job
    uses: kirandevops1993/VS-TEST-REUSABLE/.github/workflows/VStest-reusable.yml@main 
    with: 
      runsOn: "windows-latest" # This is the input required by the reusable workflow
      dotnet-version: "7.0.x" 
      test-assembly: "**/*Tests.dll" 
      test-filter-criteria: "TestCategory=Unit" 
      code-coverage-enabled: true 
      configuration: "Release" 
      platform: "x64" 
      test-run-title: "Unit Tests" 
      custom-test-adapters: "path/to/custom/adapters" 
      run-in-parallel: true 
      testPlan: "Plan1" 
      testSuite: "SuiteA" 
      testConfiguration: "DebugConfig" 
      tcmTestRun: "1234" 
      uiTests: false 
      sensitive-alphanumeric-info-3: "version" 
      vsTestVersion: "latest" 
      vstestLocation: "C:/vstest.console.exe" 
      otherConsoleOptions: "--verbosity normal" 
      diagnosticsEnabled: true 
      collectDumpOn: "onAbortOnly" 
      rerunFailedTests: true 
      rerunType: " runAllTestsAfterXBuilds0" \
